#!/bin/sh

# logs number of file descriptors opened by a process

watched_procname=in.emaild.mta
#watched_pid="$(pidof "$watched_procname")"
logfile=/var/log/emaild-fdcounts.log

interval_list=1
interval_log=60

timestamp () {
  date --rfc-3339=s
}

while true ; do
  max=0
  sum=0
  for i in $(seq "$interval_log") ; do
    count="$(ls "/proc/$(pidof "$watched_procname")/fd/" | wc -l)"
    : $((sum = sum + count))
    : $((max = count > max ? count : max))
    sleep "$interval_list"
  done
  printf '%s %s %d\n' "$(timestamp)" "$((sum / interval_log))" "$max"
done >>"$logfile"
